GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs
INFO:datasets:PyTorch version 2.6.0 available.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
SLURM auto-requeueing enabled. Setting signal handlers.
Traceback (most recent call last):
  File "/gpfs/users/regnaguen/Learning-point-processes/main/train/train.py", line 35, in <module>
    main()
  File "/gpfs/users/regnaguen/Learning-point-processes/main/train/train.py", line 29, in main
    plrunner.test()
  File "/gpfs/users/regnaguen/Learning-point-processes/easy_tpp/runner/trainer.py", line 205, in test
    results = trainer.test(
  File "/gpfs/workdir/regnaguen/LTPP/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 775, in test
    return call._call_and_handle_interrupt(
  File "/gpfs/workdir/regnaguen/LTPP/lib/python3.9/site-packages/pytorch_lightning/trainer/call.py", line 48, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/gpfs/workdir/regnaguen/LTPP/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 817, in _test_impl
    results = self._run(model, ckpt_path=ckpt_path)
  File "/gpfs/workdir/regnaguen/LTPP/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1012, in _run
    results = self._run_stage()
  File "/gpfs/workdir/regnaguen/LTPP/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1049, in _run_stage
    return self._evaluation_loop.run()
  File "/gpfs/workdir/regnaguen/LTPP/lib/python3.9/site-packages/pytorch_lightning/loops/utilities.py", line 179, in _decorator
    return loop_run(self, *args, **kwargs)
  File "/gpfs/workdir/regnaguen/LTPP/lib/python3.9/site-packages/pytorch_lightning/loops/evaluation_loop.py", line 145, in run
    self._evaluation_step(batch, batch_idx, dataloader_idx, dataloader_iter)
  File "/gpfs/workdir/regnaguen/LTPP/lib/python3.9/site-packages/pytorch_lightning/loops/evaluation_loop.py", line 437, in _evaluation_step
    output = call._call_strategy_hook(trainer, hook_name, *step_args)
  File "/gpfs/workdir/regnaguen/LTPP/lib/python3.9/site-packages/pytorch_lightning/trainer/call.py", line 328, in _call_strategy_hook
    output = fn(*args, **kwargs)
  File "/gpfs/workdir/regnaguen/LTPP/lib/python3.9/site-packages/pytorch_lightning/strategies/strategy.py", line 425, in test_step
    return self.lightning_module.test_step(*args, **kwargs)
  File "/gpfs/users/regnaguen/Learning-point-processes/easy_tpp/models/basemodel.py", line 411, in test_step
    one_step_metrics = one_step_metrics_compute.compute_all_metrics(
  File "/gpfs/users/regnaguen/Learning-point-processes/easy_tpp/evaluate/metrics_compute.py", line 61, in compute_all_metrics
    return self._compute_prediction_metrics(batch, pred)
  File "/gpfs/users/regnaguen/Learning-point-processes/easy_tpp/evaluate/metrics_compute.py", line 74, in _compute_prediction_metrics
    metrics['type_accuracy'] = self.calculate_type_accuracy(masked)
  File "/gpfs/users/regnaguen/Learning-point-processes/easy_tpp/evaluate/metrics_compute.py", line 135, in calculate_type_accuracy
    accuracy_metric.update(masked.pred_types, masked.true_types)
  File "/gpfs/workdir/regnaguen/LTPP/lib/python3.9/site-packages/torchmetrics/metric.py", line 559, in wrapped_func
    raise err
  File "/gpfs/workdir/regnaguen/LTPP/lib/python3.9/site-packages/torchmetrics/metric.py", line 549, in wrapped_func
    update(*args, **kwargs)
  File "/gpfs/workdir/regnaguen/LTPP/lib/python3.9/site-packages/torchmetrics/classification/stat_scores.py", line 339, in update
    _multiclass_stat_scores_tensor_validation(
  File "/gpfs/workdir/regnaguen/LTPP/lib/python3.9/site-packages/torchmetrics/functional/classification/stat_scores.py", line 322, in _multiclass_stat_scores_tensor_validation
    raise RuntimeError(
RuntimeError: Detected more unique values in `preds` than expected. Expected only 2 but found 3 in `preds`. Found values: tensor([0, 1, 2], device='cuda:0').
srun: error: ruche-gpu13: task 0: Exited with exit code 1
